name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare folder with only load.py
        run: |
          mkdir EDMC-LogEventMiner
          cp load.py EDMC-LogEventMiner/

      - name: Create zip with just that folder
        run: |
          zip -j -r EDMC-LogEventMiner.zip EDMC-LogEventMiner

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: EDMC-LogEventMiner.zip
